UserSearch/UserSearchModal.js

Resolves UICHKOUT-46:
This passes onCloseModal forward to the User props as onComponentWillUnmount. This depends on other PRs: [ui-checkout](https://github.com/folio-org/ui-checkout/pull/55), [ui-users](ui-users), [stripes-smart-components](https://github.com/folio-org/stripes-smart-components/pull/80)

Uichkout 46

---

CHANGELOG.md
UserSearch/UserSearchModal.js

Restore the behavior of this plugin previous to [UIIN-58](https://issues.folio.org/browse/UIIN-58). This means a user-search that results in a single row will simply show that row, as before, rather than redirecting the browser to the user-details page for that row.
Refs [STSMACOM-52](https://issues.folio.org/browse/STSMACOM-52). Fixes [UIREQ-60](https://issues.folio.org/browse/UIREQ-60), [UICHKOUT-54](https://issues.folio.org/browse/UICHKOUT-54), [UIU-373](https://issues.folio.org/browse/UIU-373).

Turn SearchAndSort's show-single-result off

---

UserSearch/UserSearch.js

Allow `PropTypes.node` instead of the more restrictive
`PropTypes.string` for labels that may be passed as `<FormattedMessage>`
objects.

allow PropTypes.node for labels

---

CHANGELOG.md
UserSearch/UserSearch.js

Accept a prop for the element id of the find-user button. This allows
pages that may have multiple instances of the plugin to make sure each
find-user button has a unique ID.
Refs [UIU-884](https://issues.folio.org/browse/UIU-884)

accept id attribute for find-user button

---

CHANGELOG.md
UserSearch/UserSearchModal.js

This PR passes a correct `packageInfo` into `Users`. This change is required to fix https://issues.folio.org/browse/ERM-72 and it's related to couple additional PRs in ui-users (https://github.com/folio-org/ui-users/pull/761) and `SearchAndSort` (https://github.com/folio-org/stripes-smart-components/pull/450).

Pass correct packageInfo into Users. Part of ERM-72.

---

CHANGELOG.md
src/filterConfig.js
test/bigtest/interactors/findUser.js

The active and inactive filters were restored to ui-users in
/folio-org/ui-users/pull/811. This change restores them here as well.

restore active, inactive filters

---

src/PluginFindUser.js
test/bigtest/tests/findUser-test.js

To allow user navigate to patron look-up link by keyboard
https://issues.folio.org/browse/UICHKOUT-509
#Screenshot

UICHKOUT-509 - Keyboard navigation ignores Patron look-up link

---

src/UserSearchView.js

Don't send an unnecessary boolean value to `<AppIcon>`. It generates a
console warning.
Fixes [UIPFU-18](https://issues.folio.org/browse/UIPFU-18)

UIPFU-18 provide correct props to AppIcon

---

src/PluginFindUser.js

`marginBottom0` is being used when computing the CSS style for the _wrapper_, but the the `Button` itself still applies one even if `marginBottom0={true}` is passed into the plugin.

Pass marginBottom0 through to the <Button>

---

src/PluginFindUser.js
src/UserSearchModal.js

refs UIPFU-23
needs to be merged after https://github.com/folio-org/stripes-components/pull/1115 is merged.
PR targets the ref to the `Modal` instead of the Modals content because the condition [here](https://github.com/folio-org/ui-plugin-find-user/pull/112/files#diff-96e3556dd15eba52e6c744f5d35fd2eeR56) needs to not only consider elements within the Modals content but even outside (the dismissible button in this case). So that when we close a modal by clicking the **X** button the button that triggered the opening of the modal should be back into focus.

Pass a ref to the Modal instead of the Modal content, refs UIPFU-23

---

src/PluginFindUser.js

Added the `renderTrigger` optional render function for the button to open the user search modal. This function can be used to pass back the `ref` for the trigger button back to the parent to focus the it, for example: whenever a new field is rendered as a part of a repeatableField

Add renderTrigger conditional function, refs ERM-620

---

package.json
test/bigtest/index.js

Upgrade babel deps to those compatible with v7. This is part of a
project-wide effort to update the build infrastructure.
Refs [UIPFU-25](https://issues.folio.org/browse/UIPFU-25)

UIPFU-25 upgrade babel deps

---

CHANGELOG.md
package.json

A stripes module can be more than one type, presenting an array in
`actsAs` rather than a single string to `type`.
Refs [STCOR-148](https://issues.folio.org/browse/STCOR-148)

STCOR-148 migrate to actsAs

---

package.json

Forgot to remove `babel-polyfill` in #120 when we upgrade to other
babel-7 deps.

STCOR-381 remove unused libraries

---

CHANGELOG.md
package.json
src/UserSearchModal.js
src/UserSearchView.js
src/filterConfig.js

* UIPFU-22 -- Patron group column display is incorrect
* IPFU-26 -- Active and Inactive filters use translations from ui-users
Also provide a missing propType to get clean ESLint output.

Fix two bugs: UIPFU-22 and UIPFU-26

---

CHANGELOG.md
src/UserSearchContainer.js
src/filterConfig.js

Addressed this by defining a separate displayName in the FiterGroup
values when they are mapped on component load, which displays the
unmodified user group name.  Then wrapped a javascript encodeURIComponent
function around the internal identifier group name
to encode any special characters (such as spaces and commas).
This seems to have fixed the problem, user groups with commas in the
names can now be selected normally and will pull up user names in the
modal.
Refs: https://issues.folio.org/browse/UIPFU-28

UIPFU-28: Can't filter requester lookup by patron group with commas

---

CHANGELOG.md
package.json

Update `@folio/stripes` to `v5`, which also includes updates to
`react-intl` `v5.7` and `react-router` `v5.1`.
Refs [UIPFU-30](https://issues.folio.org/browse/UIPFU-30)

UIPFU-30 update @folio/stripes to v5

---

CHANGELOG.md
src/UserSearchContainer.js

Retrieve up to 200 patron groups, the same limit set in [ui-users](https://github.com/folio-org/ui-users/blob/993b5a902244b2b418e62f6b1021e0ace28ad282/src/routes/UserSearchContainer.js).
Refs [UIPFU-33](https://issues.folio.org/browse/UIPFU-33)

UIPFU-33 retrieve up to 200 patron groups

---

CHANGELOG.md
src/Filters.js
src/UserSearchContainer.js
src/UserSearchView.js

https://issues.folio.org/browse/UIPFU-35
Fix the inconsistent search result count in the user search popup.
There are two ways.
The first is to try to repair the implemented one (using `resultCount`, which re-requests all previously fetched pages).
The second way is to implement the approach (using `offset`) that successfully fixed this issue in `ui-users`.
In this PR, the second path was chosen.

UIPFU-35: Use offset to request result list pages

---

.eslintrc
CHANGELOG.md
package.json
src/UserSearchView.js

- Display preferred name in the user search modal in Checkout and Requests
- If user has `preferredFirstName` then display `LastName`, `PreferredFirstName` `(FirstName)` `MiddleName` in result list
- if user doesn't have  `preferredFirstName` then display `LastName`, `FirstName` `MiddleName` in result list
- Refs: https://issues.folio.org/browse/UIU-2503
- Refactor `getFullName` function to include `preferredFirstName`
- Added `eslint-import-resolver-webpack` plugin to resolve eslint error `unable to resolve path to module`. See in screenshots

UIU-2503: Display preferred name in Checkout and Requests user modal

---

CHANGELOG.md
src/UserSearchModal.js

We have feedback from customer, that in the `ui-checkout` module when patron is set using `find-user` plugin, sometimes plugin button `Patron look-up` becomes focused instead of `item barcode` input.
I investigated this problem and found out that the issue is reproducible only with fast internet connection.
When we select user in `find-user` plugin modal then this modal is closed. When this modal is closed it restores focus to element which had focus before opening modal(in our case it is button `Patron look-up`). Then patron info is loaded from backend and after that we set focus to `item barcode` input.
But sometimes(when you have fast internet connection) patron info is loaded before modal becomes closed. So in this case we first set focus to `item barcode` input then modal becomes …

UIPFU-48: Resolve problem with focus after modal close

---

CHANGELOG.md
src/UserSearchContainer.js

When conducting a search, query against the same fields as the users
app. This means adding
* `personal.preferredFirstName`
* `customFields`
Refs [UIPFU-55](https://issues.folio.org/browse/UIPFU-55)

UIPFU-55 also query against preferredName, customFields

---

CHANGELOG.md
src/Filters.js
src/UserSearchContainer.js

https://issues.folio.org/browse/UIPFU-59
Use group id instead of group name when filtering.

UIPFU-59: Use group id instead of group name when filtering

---

CHANGELOG.md
src/UserSearchContainer.js

Add middle name to keyword search for Users
Add personal.middleName to queryFields list.
https://issues.folio.org/browse/UIPFU-58

UIPFU-58 - Add middle name to keyword search for Users

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
CHANGELOG.md
package.json

update NodeJS to v16 in GitHub Actions 
https://issues.folio.org/browse/UIPFU-67

UIPFU-67 - update NodeJS to v16 in GitHub Actions

---

CHANGELOG.md
src/UserSearchView.js
test/bigtest/tests/findUser-test.js

[UIPFU-75](https://issues.folio.org/browse/UIPFU-75)
The issue was caused due to the value of unchecked users' value to `null`
- fix `checkedUsersLength` 
- 
https://github.com/folio-org/ui-plugin-find-user/assets/116072773/33cb0891-0cdb-496e-a717-3fc761578ae3
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …

UIPFU-75: fix the number of selected users length

---

CHANGELOG.md
src/UserSearchContainer.js
src/constants.js
test/bigtest/tests/findUser-test.js

https://issues.folio.org/browse/UIPFU-76
As far as the "User type" filter was [implemented](https://github.com/folio-org/ui-users/pull/2555) for the user search and currently includes "shadow" users in the results, the plugin's changes were reverted to keep consistency in the query (This ticket originally was created for consistency purposes).
Revert https://github.com/folio-org/ui-plugin-find-user/pull/241
https://github.com/folio-org/ui-plugin-find-user/assets/88109087/5205968c-27e3-433b-ab25-1907455a58bd
- What other …

UIPFU-76 Revert - ECS - 'Do not display shadow users in search results'

---

CHANGELOG.md
src/PluginFindUser.js
src/UserSearchContainer.js
src/UserSearchView.js
src/utils.js

[UIPFU-87](https://folio-org.atlassian.net/browse/UIPFU-87) - Fix User Search Modal pagination issue.
The fix includes :-
-> displaying load more button when filtered data > 100.
-> showing correct filtered data count in sub-header (below User Search Results heading).
https://github.com/folio-org/ui-plugin-find-user/assets/105021655/e8ce5005-c381-4d8a-8fb9-370d847cd73a
Test cases were not covered initially.
We will gradually migrate unit tests in this module to Jest/RTL .
- Do …

UIPFU-87 - Fix User Search Modal pagination issue.

---

yarn.lock

* `follow-redirects` < `1.15.4` is vulnerable to CVE-2023-26159,
CVE-2024-28849
* `es5-ext` < `0.10.63` is vulnerable to CVE-2024-27088
* `color-string` < 1.5.5 is vulnerable to CVE-2021-29060
* `webpack-dev-middleware` < 5.3.4 is vulnerable to CVE-2024-29180
* `express` < 4.19.2 is vulnerable to CVE-2024-29041

CVE-2023-26159 CVE-2024-28849 CVE-2024-27088 mitigation 

---

CHANGELOG.md
test/jest/__mock__/index.js
test/jest/__mock__/intl.mock.js
test/jest/__mock__/stripes.mock.js
test/jest/__mock__/stripesComponents.mock.js
test/jest/__mock__/stripesConfig.mock.js
test/jest/__mock__/stripesCore.mock.js
test/jest/__mock__/stripesSmartComponents.mock.js
test/jest/setupFiles.js

[UIPFU-78](https://folio-org.atlassian.net/browse/UIPFU-78) - Create Jest test environment and setup initial mocks.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

UIFPU-78 - Create jest environment and setup initial mocks

---

CHANGELOG.md
src/UserSearchContainer.js

[UIPFU-95](https://folio-org.atlassian.net/browse/UIPFU-95) - Use keywords CQL field for keyword user search
The /users API has a new CQL search index keywords that significantly speeds up the search. This [implementation](https://folio-org.atlassian.net/browse/MODUSERS-457) bumped up users interface from 16.2 to 16.3 and it is backwards compatible.
Hence search query is updated to leverage the new search index.
- Are the JIRAs …

UIPFU-95 - Use keywords CQL field for keyword user search.

---

CHANGELOG.md
src/UserSearchContainer.js

update change log file to reflect a release for Q CSP#4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to …

UIPFU-97 - update change log file to reflect a release for Q CSP#4

---

CHANGELOG.md
src/PluginFindUser.js
src/PluginFindUser.test.js

[UIPFU-82](https://folio-org.atlassian.net/browse/UIPFU-82)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers …

UIPFU-82 - add jest test cases for PluginFindUser.js

---

CHANGELOG.md
src/UserSearchModal.js

https://folio-org.atlassian.net/browse/UIPFU-100
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help …

UIPFU-100 Add modal title prop support

---

CHANGELOG.md
src/UserSearchView.js
src/UserSearchView.test.js
src/utils.js
src/utils.test.js

Unit tests for `ui-plugin-find-user/src/UserSearchView.js`.
https://folio-org.atlassian.net/browse/UIPFU-85

UIPFU-85: Migration of unit tests to Jest for ui-plugin-find-user/src/UserSearchView.js

---

CHANGELOG.md
src/UserSearchView.js
src/UserSearchView.test.js

https://folio-org.atlassian.net/browse/UIPFU-115
Explanation: as the `useState` updates are async, `reduceUsersToMap` was invoked with stale state for `isAllChecked`. Extracting the old state into a constant within the local scope and performing operations off of the constant (snapshot) state value gets rid of the issue.

UIPFU-115: Fix the algorithm for marking all users as checked/unchecked

---

CHANGELOG.md
src/UserSearchContainer.js
src/UserSearchContainer.test.js
src/constants.js
src/userUtils.js
src/utils.js
src/utils.test.js
test/jest/__mock__/stripesConfig.mock.js
test/jest/__mock__/stripesSmartComponents.mock.js

When the assigned filter is used with other filters, it just filters the already fetched users, so it only shows the assigned users from the 100 users. This is a bug because when the assigned filter is selected, it should display all the assigned users, not just from the previously fetched ones. BE doesn't support this filter, so everything should be done in the UI. So when the assigned filter is selected with other filters, the UI will filter out those users, and the same goes for sorting. The assigned users come from the `Authorization roles` app. When the assigned filter is not selected, the search will work via the API as usual.
[UIPFU-107](https://folio-org.atlassian.net/browse/UIPFU-107)
https://github.com/user-attachments/assets/e845e93a-89b7-4f17-b05a-f089baadda0f
Before merging …

UIPFU-107: Refactor user filtering logic in UserSearchContainer.
