UserSearch/UserSearchModal.js
Fixes [UIPFU-7](https://issues.folio.org/browse/UIPFU-7)
=> Import Users without routing. Fixes UIPFU-7

CHANGELOG.md, UserSearch/UserSearchModal.js, package.json
Refs [UIPFU-6](https://issues.folio.org/browse/UIPFU-6)
=> disallow user creation and editing. Refs UIPFU-6

CHANGELOG.md, UserSearch/UserSearch.js
For ui-checkout regression test to identify the button.
=> Set ID on find user button. UICHKOUT-414

CHANGELOG.md, UserSearch/UserSearch.css, UserSearch/UserSearchModal.js
Issue: https://issues.folio.org/browse/FOLIO-1418
Note: This needs to be merged in before these changes take effect:
https://github.com/folio-org/stripes-components/pull/612
=> Fixing scroll height in UserSearchModal - FOLIO-1418

UserSearch/UserSearchModal.js, package.json
Part two of https://github.com/folio-org/ui-users/pull/528
=> Update users UI path

translations/ui-plugin-find-user/ca.json, translations/ui-plugin-find-user/fr_FR.json, translations/ui-plugin-find-user/hu.json
=> Update translation strings as of 20181004T193841

translations/ui-plugin-find-user/ar.json
=> Update translation strings as of 20181031T224505

translations/ui-plugin-find-user/ar.json
=> Update translation strings as of 20181112T151205

translations/ui-plugin-find-user/pt_PT.json
=> Update translation strings as of 20181212T135930

translations/ui-plugin-find-user/en_SE.json
=> Update translation strings as of 20190110T173959

UserSearch/UserSearch.js
The title attribute should not be use for accessibility.
Refs [STCOM-296](https://issues.folio.org/browse/STCOM-296)
=> don't use the title attribute for html elements

translations/ui-plugin-find-user/ar.json, translations/ui-plugin-find-user/ca.json, translations/ui-plugin-find-user/da.json, translations/ui-plugin-find-user/de.json, translations/ui-plugin-find-user/en_GB.json, translations/ui-plugin-find-user/en_SE.json, translations/ui-plugin-find-user/en_US.json, translations/ui-plugin-find-user/es.json, translations/ui-plugin-find-user/es_ES.json, translations/ui-plugin-find-user/fr.json, translations/ui-plugin-find-user/fr_FR.json, translations/ui-plugin-find-user/hu.json, translations/ui-plugin-find-user/it_IT.json, translations/ui-plugin-find-user/pt_BR.json, translations/ui-plugin-find-user/pt_PT.json, translations/ui-plugin-find-user/zh_CN.json
=> Update translation strings as of 20190314T195719

translations/ui-plugin-find-user/ar.json, translations/ui-plugin-find-user/en_US.json, translations/ui-plugin-find-user/pt_BR.json
=> Update translation strings as of 20190321T130117

translations/ui-plugin-find-user/es_419.json
=> Update translation strings as of 20190422T163602

translations/ui-plugin-find-user/ar.json, translations/ui-plugin-find-user/ca.json, translations/ui-plugin-find-user/da.json, translations/ui-plugin-find-user/de.json, translations/ui-plugin-find-user/en_GB.json, translations/ui-plugin-find-user/en_SE.json, translations/ui-plugin-find-user/en_US.json, translations/ui-plugin-find-user/es.json, translations/ui-plugin-find-user/es_419.json, translations/ui-plugin-find-user/es_ES.json, translations/ui-plugin-find-user/fr.json, translations/ui-plugin-find-user/fr_FR.json, translations/ui-plugin-find-user/hu.json, translations/ui-plugin-find-user/it_IT.json, translations/ui-plugin-find-user/pt_BR.json, translations/ui-plugin-find-user/pt_PT.json, translations/ui-plugin-find-user/zh_CN.json
=> Update translation strings as of 20190426T133506

translations/ui-plugin-find-user/en.json
Fix "inactive" status presentation according to the comments in the story - UIU-973. https://issues.folio.org/browse/UIU-973
=> UIU-973: Fix inactive status presentation.

translations/ui-plugin-find-user/ca.json, translations/ui-plugin-find-user/da.json, translations/ui-plugin-find-user/de.json, translations/ui-plugin-find-user/en_GB.json, translations/ui-plugin-find-user/en_SE.json, translations/ui-plugin-find-user/en_US.json, translations/ui-plugin-find-user/es.json, translations/ui-plugin-find-user/es_419.json, translations/ui-plugin-find-user/fr.json, translations/ui-plugin-find-user/fr_FR.json, translations/ui-plugin-find-user/hu.json, translations/ui-plugin-find-user/it_IT.json, translations/ui-plugin-find-user/pt_PT.json, translations/ui-plugin-find-user/zh_CN.json
=> Update translation strings as of 20190502T175244

CHANGELOG.md, src/UserSearch.css, src/UserSearchView.js
Same as https://github.com/folio-org/ui-users/pull/826
=> UIU-973: Add user status indication.

translations/ui-plugin-find-user/pt_BR.json
=> Update translation strings as of 20190503T205536

translations/ui-plugin-find-user/ar.json, translations/ui-plugin-find-user/ca.json, translations/ui-plugin-find-user/da.json, translations/ui-plugin-find-user/de.json, translations/ui-plugin-find-user/en_GB.json, translations/ui-plugin-find-user/en_SE.json, translations/ui-plugin-find-user/en_US.json, translations/ui-plugin-find-user/es.json, translations/ui-plugin-find-user/es_419.json, translations/ui-plugin-find-user/es_ES.json, translations/ui-plugin-find-user/fr.json, translations/ui-plugin-find-user/fr_FR.json, translations/ui-plugin-find-user/hu.json, translations/ui-plugin-find-user/it_IT.json, translations/ui-plugin-find-user/pt_BR.json, translations/ui-plugin-find-user/pt_PT.json, translations/ui-plugin-find-user/zh_CN.json
=> Update translation strings as of 20190718T013203

CHANGELOG.md, src/UserSearchContainer.js, src/filterConfig.js
Tokenize the search terms, just like ui-users does.
Fixes [UIPFU-17](https://issues.folio.org/browse/UIPFU-17)
=> UIPFU-17 tokenize search terms

translations/ui-plugin-find-user/it_IT.json
=> Update translation strings as of 20190823T083240

src/UserSearchView.js
for the consistency among the platform status column was renamed(as it is in the ui-users module). Also, `SearchAndSortQuery` component uses a column name as a query parameter for sorting.
=> UIPFU-16: Change column name.

translations/ui-plugin-find-user/it_IT.json
=> Update translation strings as of 20190828T124751

translations/ui-plugin-find-user/zh_CN.json
=> Update translation strings as of 20190909T193700

src/UserSearchView.js, test/bigtest/interactors/findUser.js, test/bigtest/tests/findUser-test.js
See description at [UIAC-11](https://issues.folio.org/browse/UIAC-11)
=> UIAC-11 properly display multi user selections

translations/ui-plugin-find-user/ru.json, translations/ui-plugin-find-user/zh_TW.json
=> Update translation strings as of 20191014T135140

translations/ui-plugin-find-user/ja.json
=> Update translation strings as of 20191028T205642

translations/ui-plugin-find-user/he.json
=> Update translation strings as of 20191113T214202

translations/ui-plugin-find-user/it_IT.json
=> Update translation strings as of 20191119T231120

translations/ui-plugin-find-user/fr_FR.json
=> Update translation strings as of 20191127T181804

translations/ui-plugin-find-user/fr_FR.json, translations/ui-plugin-find-user/ru.json
=> Update translation strings as of 20191204T162855

translations/ui-plugin-find-user/es.json, translations/ui-plugin-find-user/es_419.json, translations/ui-plugin-find-user/es_ES.json
=> Update translation strings as of 20200103T213225

translations/ui-plugin-find-user/it_IT.json
=> Update translation strings as of 20200127T144839

translations/ui-plugin-find-user/ur.json
=> Update translation strings as of 20200210T220102

translations/ui-plugin-find-user/ja.json
=> Update translation strings as of 20200413T183215

translations/ui-plugin-find-user/ja.json
=> Update translation strings as of 20200420T134821

translations/ui-plugin-find-user/it_IT.json, translations/ui-plugin-find-user/zh_TW.json
=> Update translation strings as of 20200505T210535

translations/ui-plugin-find-user/zh_TW.json
=> Update translation strings as of 20200513T135229

CHANGELOG.md, package.json
=> Updated to stripes v4.0.0

translations/ui-plugin-find-user/en_SE.json, translations/ui-plugin-find-user/en_US.json
=> Update translation strings as of 20200615T161518

CHANGELOG.md, package.json
I updated the eslint version in package.json. I then re-ran yarn lint
to make sure the new version didn't flag any problems with the existing
code.  Also updated React-intl to latest version.
Refs: https://issues.folio.org/browse/UIPFU-24
=> Update Eslint and React-intl to latest versions

translations/ui-plugin-find-user/ru.json
=> Update translation strings as of 20200624T130324

CHANGELOG.md, package.json, test/bigtest/helpers/helpers.js, test/bigtest/network/factories/addresse.js, test/bigtest/network/factories/application.js, test/bigtest/network/factories/service-points-user.js, test/bigtest/network/factories/user-personal.js, test/bigtest/network/factories/user.js, test/bigtest/network/index.js, test/bigtest/network/models/addresse.js, test/bigtest/network/models/application.js, test/bigtest/network/models/service-point.js, test/bigtest/network/models/service-points-user.js, test/bigtest/network/models/user-personal.js, test/bigtest/network/models/user.js, test/bigtest/network/serializers/application.js
This is part of an on-going initiative to completely migrate all of `folio-org` projects from `@bigtest/mirage` to `miragejs`.
[`@bigtest/mirage`](https://github.com/bigtestjs/mirage/) was originally a prototype to make `mirage` available to any framework, but it has since been archived in favor of [`miragejs`](https://miragejs.com/). The documentation for `miragejs` is not only prodigious for its extensive API docs but also for its tutorials and guides. Furthermore, it receives regular bug-fixes and maintenance releases in thanks to its extremely large and active community.
Previous PR: [@folio-org/ui-oai-pmh #39](https://github.com/folio-org/ui-oai-pmh/pull/39)
_Linking the previous pull request so that subsequent ones can be found tagged below._
<details>
<summary>Overview of progress …
=> Refactor to MirageJS

CHANGELOG.md, src/UserSearchView.js
https://issues.folio.org/browse/UIPFU-31
before
after
=> UIPFU-31 UI Glitch When Opening Proxy/Sponsor Picker

translations/ui-plugin-find-user/hi_IN.json, translations/ui-plugin-find-user/ja.json, translations/ui-plugin-find-user/ko.json
=> Update translation strings as of 20200921T192032

translations/ui-plugin-find-user/ja.json, translations/ui-plugin-find-user/pl.json
=> Update translation strings as of 20200924T211627

translations/ui-plugin-find-user/zh_CN.json
=> Update translation strings as of 20200928T202231

translations/ui-plugin-find-user/it_IT.json
=> Update translation strings as of 20201008T220807

translations/ui-plugin-find-user/ja.json
=> Update translation strings as of 20201102T140138

translations/ui-plugin-find-user/ber.json
=> Update translation strings as of 20201109T135508

CHANGELOG.md, package.json
https://issues.folio.org/projects/UIPFU/issues/UIPFU-37
=> UIPFU-37: Upgrade to stripes v6

CHANGELOG.md, package.json, test/bigtest/interactors/findUser.js, test/bigtest/tests/findUser-test.js
Refs [UIPFU-44](https://issues.folio.org/browse/UIPFU-44), [UXPROD-3264](https://issues.folio.org/browse/UXPROD-3264)
=> UIPFU-44 bump stripes to v7

src/UserSearchView.js
See https://issues.folio.org/browse/UIPFU-50
=> UIPFU-50 adjust listing to reflect new listing/link patterns

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIPFU-63
=> UIPFU-63: Bump stripes to 8.0.0 for Orchid/2023-R1

CHANGELOG.md
https://issues.folio.org/browse/UIPFU-64
=> Release v6.4.0

CHANGELOG.md, package.json
Upgrade react to v18
https://issues.folio.org/browse/UIPFU-70
=> UIPFU-70 upgrade react to v18

CHANGELOG.md, package.json
Bump up major version.
Refs - [UIPFU-70](https://issues.folio.org/browse/UIPFU-70)
=> UIPFU-70 - Bump up version

CHANGELOG.md, PULL_REQUEST_TEMPLATE.md
Add PULL_REQUEST_TEMPLATE.md file to the repository.
https://issues.folio.org/browse/UIPFU-68
=> UIPFU-68 - Add PULL_REQUEST_TEMPLATE.md file to the repository.

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md
[UIPFU-73](https://issues.folio.org/browse/UIPFU-73) - Update Node.js to v18 in GitHub Actions
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> UIPFU-73 - Update Node.js to v18 in GitHub Actions

CHANGELOG.md, src/UserSearchContainer.js, src/UserSearchModal.js
Support users fetching for different tenant using plugin is scope of one tenant
Propagate tenant value from props to manifest
https://github.com/folio-org/stripes-connect/pull/221
There are no tests in this repo at all + PR is almost about props passing, so nothing to cover
Ideally all of the PRs involved in breaking changes would be merged in the same day …
=> UIPFU-74 Support fetch users from different tenants

CHANGELOG.md, package.json, yarn.lock
Refs [UIPFU-79](https://issues.folio.org/browse/UIPFU-79)
=> STRIPES-868 BREAKING bump react-intl to v6

CHANGELOG.md, package.json, src/PluginFindUser.js, src/UserSearchContainer.js, src/UserSearchView.js, src/utils.js
https://folio-org.atlassian.net/browse/UIPFU-88
This PR is to update the long-lived **b7.1 Quesnelia** with [UIPFU-87](https://folio-org.atlassian.net/browse/UIPFU-87) - Fix User Search Modal pagination issue.
Test cases were not covered initially.
We will gradually migrate unit tests in this module to Jest/RTL .
Ideally all of the PRs involved in breaking …
=> Patch Release v7.1.1

CHANGELOG.md, src/UserSearchContainer.js, src/UserSearchView.js
[UIPFU-49](https://folio-org.atlassian.net/browse/UIPFU-49) - Apply Previous/Next Pagination to Find Users plug-in results list
These updated files do not have Jest unit tests currently. We have a ticket in our backlog for this.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
=> UIPFU-49 - Apply Prev/Next Pagination

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, package.json, src/UserSearchContainer.js
This PR intends to release https://folio-org.atlassian.net/browse/UIPFU-95 for Quesnelia CSP#4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> UIPFU-95 - Use keywords CQL field for keyword user search. (#271)

CHANGELOG.md, package.json, yarn.lock
https://folio-org.atlassian.net/browse/UIPFU-109; https://folio-org.atlassian.net/browse/UIPFU-110
=> UIPFU-109, UIPFU-110: migrate stripes-* deps; react-intl to v7
